AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless application for converting XLSX payloads to PDF using the Adobe web services toolkit.

Globals:
  Function:
    Runtime: python3.13
    Handler: app.lambda_handler
    Timeout: 180
    MemorySize: 256
    Architectures:
      - x86_64
    Tracing: Active
    Layers:
      - !If
        - UseExternalAdobeLayer
        - !Ref AdobePythonLayerArn
        - !Ref AdobePdfServicesLayer

Parameters:
  AdobePythonLayerArn:
    Type: String
    Default: ""
    Description: Optional ARN for an external Adobe PDF Services Python layer.
  ApiStage:
    Type: String
    Default: Prod
    AllowedPattern: '^[A-Za-z0-9_-]+$'
    Description: Stage name for the API Gateway deployment.
  PDFServicesClientIdParameterPath:
    Type: String
    Default: /pdfservices/client/id
    Description: SSM parameter path containing the Adobe PDF Services client identifier.
  PDFServicesClientSecretParameterPath:
    Type: String
    Default: /pdfservices/client/secret
    Description: SSM parameter path containing the Adobe PDF Services client secret.

  UseSharedAdobePythonLayer:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
    Description: Toggle to force usage of the shared Adobe Python layer instead of the bundled layer.

Conditions:
  UseExternalAdobeLayer: !Equals [!Ref UseSharedAdobePythonLayer, 'true']

Resources:

  AdobePdfServicesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-adobe-pdfservices
      Description: Bundled Adobe PDF Services SDK v4 for Python.
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.13
        - python3.12
        - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.13

  XLSToPDFApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api
      StageName: !Ref ApiStage
      BinaryMediaTypes:
        - application/pdf  # ensure PDF responses are treated as binary
        - application/octet-stream  # cover generic binary fallbacks
      EndpointConfiguration: REGIONAL
      TracingEnabled: true

  XLSToPDFDropzoneBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'xlsx-to-pdf-dropzone'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  XLSToPDF:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-xls-to-pdf
      Description: Convert XLSX payloads to PDF using the Adobe web services toolkit either synchronously via API or asynchronously via SQS.
      CodeUri: src/
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref XLSToPDFDropzoneBucket
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${PDFServicesClientIdParameterPath}
                - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${PDFServicesClientSecretParameterPath}
      Environment:
        Variables:
          DEFAULT_TARGET_BUCKET: !Ref XLSToPDFDropzoneBucket
          PDF_SERVICES_CLIENT_ID_PARAMETER: !Ref PDFServicesClientIdParameterPath
          PDF_SERVICES_CLIENT_SECRET_PARAMETER: !Ref PDFServicesClientSecretParameterPath
      Events:
        ApiInvocation:
          Type: Api
          Properties:
            RestApiId: !Ref XLSToPDFApi
            Stage: !Ref ApiStage
            Path: /xls-to-pdf
            Method: post

Outputs:
  ApiInvokeUrl:
    Description: API endpoint for synchronous XLSX to PDF conversions.
    Value:
      !Sub
        - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/xls-to-pdf
        - ApiId: !Ref XLSToPDFApi
          Stage: !Ref ApiStage
  ApiId:
    Description: API Gateway ID backing the synchronous endpoint.
    Value: !Ref XLSToPDFApi
