AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless application for converting XLSX payloads to PDF using the Adobe web services toolkit.

Globals:
  Function:
    Runtime: python3.13
    Timeout: 180
    MemorySize: 256
    Architectures:
      - x86_64
    Tracing: Active
    Layers:
      - !If
        - UseExternalAdobeLayer
        - !Ref AdobePythonLayerArn
        - !Ref AdobePdfServicesLayer

Parameters:
  AdobePythonLayerArn:
    Type: String
    Default: ""
    Description: Optional ARN for an external Adobe PDF Services Python layer.
  ApiStage:
    Type: String
    Default: Prod
    AllowedPattern: '^[A-Za-z0-9_-]+$'
    Description: Stage name for the API Gateway deployment.
  PDFServicesClientIdParameterPath:
    Type: String
    Default: /pdfservices/client/id
    Description: SSM parameter path containing the Adobe PDF Services client identifier.
  PDFServicesClientSecretParameterPath:
    Type: String
    Default: /pdfservices/client/secret
    Description: SSM parameter path containing the Adobe PDF Services client secret.

  UseSharedAdobePythonLayer:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
    Description: Toggle to force usage of the shared Adobe Python layer instead of the bundled layer.

  DropzoneBucketName:
    Type: String
    Default: xlsx-to-pdf-dropzone
    AllowedPattern: '^[A-Za-z0-9.-]{3,63}$'
    Description: Name of the S3 bucket used to store XLSX uploads and converted PDFs.

Conditions:
  UseExternalAdobeLayer: !Equals [!Ref UseSharedAdobePythonLayer, 'true']

Resources:

  AdobePdfServicesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${AWS::StackName}-adobe-pdfservices
      Description: Bundled Adobe PDF Services SDK v4 for Python.
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.13
        - python3.12
        - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.13

  XLSToPDFApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-api
      StageName: !Ref ApiStage
      BinaryMediaTypes:
        - application/pdf  # ensure PDF responses are treated as binary
        - application/octet-stream  # cover generic binary fallbacks
      EndpointConfiguration: REGIONAL
      TracingEnabled: true

  XLSToPDFDropzoneBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DropzoneBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  XLSToPDFSubmitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-submit
      Description: Accept XLSX uploads, store them in the dropzone bucket, and return the polling key.
      CodeUri: src/
      Handler: submit_handler.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DropzoneBucketName
      Environment:
        Variables:
          DEFAULT_TARGET_BUCKET: !Ref DropzoneBucketName
      Events:
        SubmitApi:
          Type: Api
          Properties:
            RestApiId: !Ref XLSToPDFApi
            Stage: !Ref ApiStage
            Path: /submit
            Method: post

  XLSToPDFGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-get
      Description: Look up conversion results and return PDFs once available.
      CodeUri: src/
      Handler: get_handler.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DropzoneBucketName
      Environment:
        Variables:
          DEFAULT_TARGET_BUCKET: !Ref DropzoneBucketName
      Events:
        GetApi:
          Type: Api
          Properties:
            RestApiId: !Ref XLSToPDFApi
            Stage: !Ref ApiStage
            Path: /get
            Method: get

  XLSToPDFConvertFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-convert
      Description: Convert uploaded XLSX files to PDF and write completion markers.
      CodeUri: src/
      Handler: convert_handler.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DropzoneBucketName
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${PDFServicesClientIdParameterPath}
                - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${PDFServicesClientSecretParameterPath}
      Environment:
        Variables:
          DEFAULT_TARGET_BUCKET: !Ref DropzoneBucketName
          PDF_SERVICES_CLIENT_ID_PARAMETER: !Ref PDFServicesClientIdParameterPath
          PDF_SERVICES_CLIENT_SECRET_PARAMETER: !Ref PDFServicesClientSecretParameterPath
      Events:
        UploadTrigger:
          Type: S3
          Properties:
            Bucket: !Ref XLSToPDFDropzoneBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .xlsx

Outputs:
  SubmitApiInvokeUrl:
    Description: API endpoint for submitting XLSX workbooks for conversion.
    Value:
      !Sub
        - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/submit
        - ApiId: !Ref XLSToPDFApi
          Stage: !Ref ApiStage
  GetApiInvokeUrl:
    Description: API endpoint for retrieving the resulting PDF once conversion completes.
    Value:
      !Sub
        - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/get
        - ApiId: !Ref XLSToPDFApi
          Stage: !Ref ApiStage
  ApiId:
    Description: API Gateway ID backing the asynchronous workflow.
    Value: !Ref XLSToPDFApi
